version: "3.8"
services:
  websocket-server:
    build: .
    ports:
      - "3005:3005"
    environment:
      - NODE_ENV=production
      - PORT=3005
      - DATABASE_URL=${DATABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - SUPABASE_URL=${SUPABASE_URL}
    restart: unless-stopped
    volumes:
      - ./recordings:/app/recordings
    env_file:
      - .env
