version: "3.8"
services:
  websocket-server:
    build: .
    ports:
      - "3005:3005"
    environment:
      - NODE_ENV=production
      - PORT=3005
    restart: unless-stopped
    volumes:
      - ./recordings:/app/recordings
